# Generated by Django 2.1.8 on 2019-09-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusername', models.CharField(max_length=100, unique=True)),
                ('cname', models.CharField(max_length=255)),
                ('cemail', models.EmailField(max_length=254)),
                ('cphone', models.CharField(max_length=15)),
                ('cstreet', models.CharField(max_length=255)),
                ('csuburb', models.CharField(max_length=100)),
                ('cpostcode', models.CharField(max_length=15)),
                ('cstate', models.CharField(max_length=100)),
            ],
        ),
    ]
